# Generated by Django 4.1.3 on 2022-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedslogan',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='sloganbody',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
