# Generated by Django 4.1.3 on 2022-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_deletedslogan_image_alter_sloganbody_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedslogan',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='sloganbody',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
