# Generated by Django 4.1.3 on 2022-11-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_deletedslogan_image_alter_sloganbody_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_img', models.ImageField(upload_to='img')),
                ('bd_title', models.CharField(max_length=100)),
                ('button1N', models.CharField(max_length=100)),
                ('button2N', models.CharField(max_length=100)),
                ('button1L', models.CharField(max_length=100)),
                ('button2L', models.CharField(max_length=100)),
                ('AU_img', models.ImageField(upload_to='img')),
                ('Au_text', models.TextField()),
                ('aU_title', models.CharField(max_length=100)),
                ('aU_details', models.TextField()),
                ('banner1T', models.CharField(max_length=100)),
                ('banner1PD', models.CharField(max_length=100)),
                ('banner2T', models.CharField(max_length=100)),
                ('banner2PD', models.CharField(max_length=100)),
            ],
        ),
    ]
