# Generated by Django 4.1.3 on 2022-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_contactme_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('top_text', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_1_title', models.CharField(max_length=100)),
                ('banner_1_details', models.TextField()),
                ('banner_2_title', models.CharField(max_length=100)),
                ('banner_2_details', models.TextField()),
                ('banner_3_title', models.CharField(max_length=100)),
                ('banner_3_details', models.TextField()),
                ('banner_4_title', models.CharField(max_length=100)),
                ('banner_4_details', models.TextField()),
            ],
        ),
    ]
