# Generated by Django 4.1.3 on 2022-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_addproducts_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='productId',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
