# Generated by Django 4.1.3 on 2022-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_addproducts_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproducts',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
