# Generated by Django 4.1.3 on 2022-11-22 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_addproducts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='productId',
            field=models.UUIDField(default=uuid.UUID('592dd7ca-8508-43d3-984e-a0e655a32619'), editable=False, primary_key=True, serialize=False),
        ),
    ]
