# Generated by Django 4.1.3 on 2022-11-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_alter_addproducts_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproducts',
            name='productId',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='farm.addproducts'),
        ),
    ]
