# Generated by Django 4.1.3 on 2022-11-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_contact_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('profile_picture', models.ImageField(upload_to='img')),
                ('description', models.TextField()),
                ('claint_name', models.CharField(max_length=100)),
            ],
        ),
    ]
