# Generated by Django 4.1.3 on 2022-11-23 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_rename_testimonia_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('postId', models.UUIDField(default=uuid.UUID('98fcef0c-e834-4553-a73f-6d213b17b8e1'), editable=False, primary_key=True, serialize=False)),
                ('background', models.ImageField(blank=True, null=True, upload_to='img')),
                ('button_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('button_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('button_1_link', models.CharField(blank=True, max_length=100, null=True)),
                ('button_2_link', models.CharField(blank=True, max_length=100, null=True)),
                ('post_image1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('post_image2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
