# Generated by Django 4.1.3 on 2022-11-23 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('7d1a4a29-5cc8-4aaf-b15d-cc733710d0d0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
