# Generated by Django 4.1.3 on 2022-11-24 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0019_posts_id_alter_posts_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('81429623-47cf-4340-85d0-8caf5983c6de'), editable=False, primary_key=True, serialize=False),
        ),
    ]
