# Generated by Django 4.1.3 on 2022-11-24 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0020_messageme_alter_posts_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('b2c63c56-250d-4192-8862-3e80e5890385'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='post_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentId', models.ForeignKey(default=uuid.UUID('eaecabc7-dc3b-4ca7-9c4e-14e75d736f30'), on_delete=django.db.models.deletion.CASCADE, to='farm.posts', unique=True)),
            ],
        ),
    ]
