# Generated by Django 4.1.3 on 2022-11-24 13:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_alter_post_comments_commentid_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('9741ce8e-49a6-460e-a7fd-b61850cdcc3c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('b077bc79-69fe-4222-b586-510548b3b329'), editable=False, primary_key=True, serialize=False),
        ),
    ]
