# Generated by Django 4.1.3 on 2022-11-24 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_rename_post_post_comments_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('e6d5b03b-3bc1-4ddd-af9a-df4dd5e47924'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('52f19a7e-51a6-4df7-98e6-32962daed1a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
