# Generated by Django 4.1.3 on 2022-11-26 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0033_alter_posts_postid_comments_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_reply',
            old_name='comment',
            new_name='reply',
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('bd6313f0-200b-46bb-9e06-7a907239a051'), editable=False, primary_key=True, serialize=False),
        ),
    ]
