# Generated by Django 4.1.3 on 2022-11-26 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0037_alter_comments_reply_parent_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_reply',
            name='childrens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('cd4f39fa-cd06-4c98-bd3c-05b7952def79'), editable=False, primary_key=True, serialize=False),
        ),
    ]
