# Generated by Django 4.1.3 on 2022-12-02 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0039_alter_comments_reply_childrens_alter_posts_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post_comments',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('cc9d52ea-7d98-488c-bab7-323761e56d4e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
