# Generated by Django 4.1.3 on 2022-12-02 09:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0040_chat_alter_post_comments_options_alter_posts_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.CharField(default='room', max_length=1000000),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(default='user', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('38068eee-235d-4611-b290-caff2ef27df2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
