# Generated by Django 4.1.3 on 2022-12-11 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0054_alter_posts_postid_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('e0d61ffa-d200-4b13-885f-bc6707dd74d5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
