# Generated by Django 4.1.4 on 2022-12-13 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0055_alter_posts_postid_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_reply',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post_comments',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('fc342f75-0d8b-4ad7-ba03-7e39f6415ca3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
