# Generated by Django 4.1.4 on 2022-12-20 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0058_alter_posts_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('8b449ebf-fd61-4d7b-81ff-d059a4073cab'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('a0d3d77a-7a88-4086-aba8-60fc10a3c5a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
