# Generated by Django 4.1.4 on 2022-12-20 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0059_remove_orderedproduct_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('718b3976-f045-484a-b37c-cb87fc2f1647'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('3c8a3c8c-7ee9-419e-a567-32e4663f8270'), editable=False, primary_key=True, serialize=False),
        ),
    ]
