# Generated by Django 4.1.4 on 2022-12-20 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0060_orderedproduct_qty_alter_orderedproduct_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('1a3ecdb8-b183-4bd2-9edd-f77664357f62'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('4f49c880-2908-42f3-bfa5-4171fd7750f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
