# Generated by Django 4.1.4 on 2022-12-20 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0061_alter_orderedproduct_order_id_alter_posts_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('aa5bde00-7196-4d0d-a221-9557223a9a97'), editable=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('e7f9f5c9-a282-4725-af3f-20ff90cb5d77'), editable=False, primary_key=True, serialize=False),
        ),
    ]
