# Generated by Django 4.1.4 on 2022-12-20 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0062_orderedproduct_id_alter_orderedproduct_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('937d3130-2ad5-4301-a316-89bf8c912160'), editable=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('e7b90a71-dea0-4476-890c-621629ee2f90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
