# Generated by Django 4.1.4 on 2022-12-20 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0063_alter_orderedproduct_order_id_alter_posts_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('d8da97d1-c769-4b14-bb38-222a8c7d0fd7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('86d39af3-aa4e-4e62-9f3e-7efe60b9e459'), editable=False, primary_key=True, serialize=False),
        ),
    ]
