# Generated by Django 4.1.4 on 2022-12-20 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0064_remove_orderedproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('3b4c1fc4-e5c9-4a94-bb65-9065ccaebdce'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('f4998455-b16d-49cb-a910-fa90bb33ebe6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
