# Generated by Django 4.1.4 on 2022-12-20 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0065_alter_orderedproduct_order_id_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('d1d301a9-9ef3-4acb-a05c-4010991b608c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='orderedProduct',
        ),
    ]
