# Generated by Django 4.1.4 on 2022-12-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0066_alter_posts_postid_delete_orderedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('2d8f09d3-2369-4fb3-a138-93423b6e4f86'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='orderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=9000000)),
                ('items', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
                ('order_id', models.UUIDField(default=uuid.UUID('16a000cb-9f47-4198-90a0-34533ba1255e'), editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.addproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
