# Generated by Django 4.1.4 on 2022-12-20 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0067_alter_posts_postid_orderedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('3a952a0e-93a1-4d32-bc00-fd976919ed64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
