# Generated by Django 4.1.4 on 2022-12-20 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0068_alter_orderedproduct_order_id_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order_id',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('d3d9da7a-59c7-496c-9a37-6ded61357fd6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
