# Generated by Django 4.1.4 on 2022-12-20 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0069_alter_orderedproduct_order_id_alter_posts_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(default='Received', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('431da35e-2d73-45ee-b73d-354f5cd4cfc0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
