# Generated by Django 4.1.3 on 2022-11-24 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_remove_posts_id_alter_posts_postid_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='image',
            field=models.ImageField(default='img/deafult.png', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='commentId',
            field=models.ForeignKey(default=uuid.UUID('fd62de14-cdcd-4149-b7e6-6307a9bd83e6'), on_delete=django.db.models.deletion.CASCADE, to='farm.posts', unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('80647769-3d5b-467d-8f68-1611121c3c5b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
