# Generated by Django 4.1.3 on 2022-11-24 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_post_comment_image_alter_post_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='commentId',
            field=models.ForeignKey(default=uuid.UUID('78da7fa8-4be5-45e9-82d6-2d65050461f2'), on_delete=django.db.models.deletion.CASCADE, to='farm.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('cdddf638-dfd6-431d-af14-2a8e56d17893'), editable=False, primary_key=True, serialize=False),
        ),
    ]
