# Generated by Django 4.1.3 on 2022-11-24 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0023_alter_post_comment_commentid_alter_posts_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_comments',
            fields=[
                ('commentId', models.UUIDField(default=uuid.UUID('33ca23ee-c8af-4911-9b55-a71c25bb56fd'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='img/deafult.png', upload_to='img')),
                ('number', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('6adb9927-2980-4088-8b35-cd82c9c3c525'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='post_comment',
        ),
        migrations.AddField(
            model_name='post_comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.posts'),
        ),
    ]
