# Generated by Django 4.1.3 on 2022-11-24 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0024_post_comments_alter_posts_postid_delete_post_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comments',
            name='commentId',
            field=models.UUIDField(default=uuid.UUID('117a4ec0-8ec3-4636-bb97-baa55b76c7d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('fee8f8d8-62f8-4e51-958c-6c83c57dbed6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
