# Generated by Django 4.1.3 on 2022-11-24 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0030_alter_post_comments_commentid_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('46c079fd-7072-4f4f-b3cb-a67f96e5c48c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
