# Generated by Django 4.1.3 on 2022-11-24 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0031_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('b6ccf919-171c-4e3e-b7f2-420dfcd932bd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
