# Generated by Django 4.1.3 on 2022-11-26 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0035_alter_comments_reply_childrens_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_reply',
            name='childrens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.comments_reply'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('3ae7f35f-164c-4398-b711-3bd41c4f4f35'), editable=False, primary_key=True, serialize=False),
        ),
    ]
