# Generated by Django 4.1.3 on 2022-11-26 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0036_alter_comments_reply_childrens_alter_posts_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_reply',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.post_comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('b1c3d687-ed0e-46cc-9501-5bec5f680eda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
