# Generated by Django 4.1.3 on 2022-12-11 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0051_alter_posts_postid_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gander',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='posts',
            name='postId',
            field=models.UUIDField(default=uuid.UUID('cda7e8c4-4c59-449d-bbf0-6df2c2441730'), editable=False, primary_key=True, serialize=False),
        ),
    ]
